"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { ClipboardText, Plus } from "@phosphor-icons/react";
import { ResidencyDialog } from "./ResidencyDialog";
import { PhotoPicker } from "./MaintenancePanel";
import { CONDITION_LABELS as LABEL, CONDITION_VALUES, type ConditionConfig, type ConditionDetail, type ConditionItem, type ConditionList } from "@/lib/hostel-engine/condition-types";
import "./maintenance.css";
import "./conditions.css";

type Property = {id:string;name:string};
const when=(s:string)=>new Date(s).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"});
const message=(e:unknown)=>e instanceof Error?e.message:"The record could not be loaded. Try again.";
async function api<T>(url:string,method="GET",data?:object,photos:File[]=[]):Promise<T> {
 const form=new FormData();if(data)form.set("data",JSON.stringify(data));photos.forEach(file=>form.append("photos",file));
 const response=await fetch(url,{method,credentials:"same-origin",cache:"no-store",...(data?{body:form}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||"This action could not be completed. Please try again.");return result;
}
export function ConditionPanel({reference,properties=[]}:{reference?:string;properties?:Property[]}) {
 const staff=reference===undefined,endpoint=staff?"/api/console/hostel/conditions":"/api/hostel/conditions";
 const [data,setData]=useState<ConditionList|null>(null),[filters,setFilters]=useState({propertyId:"",status:"OPEN",q:"",disputed:""}),[search,setSearch]=useState("");
 const [page,setPage]=useState(1),[error,setError]=useState(""),[loading,setLoading]=useState(false),[opening,setOpening]=useState(false),[selected,setSelected]=useState(""),[settings,setSettings]=useState(false);
 const sequence=useRef(0);
 const trigger=useRef<HTMLButtonElement|null>(null);
 const load=useCallback(async()=>{const id=++sequence.current;setLoading(true);try{const result=await api<ConditionList>(`${endpoint}?${new URLSearchParams({...filters,page:String(page),...(reference?{reference}:{})})}`);if(id===sequence.current){setData(result);setError("");}}catch(e){if(id===sequence.current)setError(message(e));}finally{if(id===sequence.current)setLoading(false);}},[endpoint,filters,page,reference]);
 useEffect(()=>{const seq=sequence;queueMicrotask(()=>void load());return()=>{seq.current++;};},[load]);
 useEffect(()=>{const timer=setTimeout(()=>{setFilters(f=>f.q===search?f:{...f,q:search});setPage(1);},300);return()=>clearTimeout(timer);},[search]);
 const filter=(key:keyof typeof filters,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1);};
 async function start(){setOpening(true);setError("");try{const result=await api<ConditionDetail>(endpoint,"POST",{reference});setSelected(result.record.id);void load();}catch(e){setError(message(e));}finally{setOpening(false);}}
 return <section className="maintenance-panel condition-panel" aria-label="Room condition records">
  <header className="maintenance-heading"><div><span className="maintenance-eyebrow"><ClipboardText size={17} aria-hidden/> ROOM HANDOVER</span><h3>{staff?"Condition records":"Your room, on record"}</h3><p>{staff?"Review move-in evidence and compare it with checkout.":"Keep a shared record of your room’s condition, from arrival to departure."}</p></div><div className="maintenance-actions"><button type="button" disabled={loading} onClick={()=>void load()}>Refresh</button>{staff&&data?.isOwner&&<button type="button" onClick={()=>setSettings(true)}>Checklist settings</button>}{!staff&&<button type="button" className="maintenance-primary" disabled={!data?.config?.canCreate||opening} onClick={event=>{trigger.current=event.currentTarget;void start();}}><Plus size={18} aria-hidden/>{opening?"Opening…":"Open current checklist"}</button>}</div></header>
  <p className="maintenance-service-note">Acknowledgment confirms receipt, not agreement with every item. An open disagreement stays visible. These records do not create charges or refunds.</p>
  {!staff&&data?.config&&!data.config.canCreate&&<p className="maintenance-muted">New checklists require a current paid stay and this feature enabled by the platform and hostel. Existing records remain available below.</p>}
  <div className="maintenance-filters"><label className="maintenance-search">Search records<input type="search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Reference, resident or room"/></label><label>Status<select value={filters.status} onChange={e=>filter("status",e.target.value)}><option value="OPEN">Open records</option><option value="">All records</option>{["DRAFT","SUBMITTED","CLARIFICATION_REQUESTED","ACKNOWLEDGED","CLOSED"].map(value=><option key={value} value={value}>{LABEL[value]}</option>)}</select></label>{staff&&<label>Property<select value={filters.propertyId} onChange={e=>filter("propertyId",e.target.value)}><option value="">All properties</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label className="maintenance-check"><input type="checkbox" checked={filters.disputed==="1"} onChange={e=>filter("disputed",e.target.checked?"1":"")}/>Open disagreements</label></div>
  {error&&<p className="residency-alert" role="alert">{error}</p>}{loading&&<p role="status">Updating condition records…</p>}
  <div className="maintenance-list" aria-busy={loading}>{data?.records.map(record=><button type="button" className="maintenance-ticket" key={record.id} onClick={event=>{trigger.current=event.currentTarget;setSelected(record.id);}}><div><span className="maintenance-reference">{record.reference} · {record.propertyName}</span><strong>{record.roomLabel} · {record.spaceLabel}</strong><span>{staff?record.studentName:record.archivedAt?"Previous room handover":"Your room handover"}</span><small>Move-in revision {record.moveInRevision} · {record.checkoutRevision?`Checkout revision ${record.checkoutRevision}`:"No checkout inspection"} · {when(record.updatedAt)}</small></div><div className="maintenance-badges"><span className="maintenance-badge">{LABEL[record.status]}</span>{record.disputeBy&&<span className="maintenance-badge is-urgent">Open disagreement</span>}{record.archivedAt&&<span className="maintenance-badge">Previous room</span>}<span className="maintenance-open">Review record →</span></div></button>)}</div>
  {data&&!data.records.length&&!loading&&<div className="maintenance-empty"><ClipboardText size={28} aria-hidden/><h4>No records in this view</h4><p>{staff?"Student submissions and transfer handovers will appear here.":"Open your current checklist to record what you find. Closed records are under All records."}</p></div>}
  {data&&data.pagination.total>0&&<nav className="residency-pagination" aria-label="Condition record pages"><span>{data.pagination.total} records · Page {data.pagination.page} of {data.pagination.pages}</span><div><button type="button" disabled={loading||data.pagination.page<=1} onClick={()=>setPage(page-1)}>Previous</button><button type="button" disabled={loading||data.pagination.page>=data.pagination.pages} onClick={()=>setPage(page+1)}>Next</button></div></nav>}
  <p className="maintenance-help"><Link href={staff?"/console/hostels/guide#conditions":"/hostel/help#conditions"}>Condition record guide &amp; AI help</Link></p>
  {selected&&<ConditionDrawer key={selected} id={selected} endpoint={endpoint} staff={staff} onClose={()=>{setSelected("");requestAnimationFrame(()=>trigger.current?.focus());}} onChanged={()=>void load()}/>}
  {settings&&<ChecklistSettings endpoint={endpoint} properties={properties} onClose={()=>setSettings(false)}/>}
 </section>;
}

type DraftItem=Omit<ConditionItem,"condition">&{condition:string};
function ConditionDrawer({id,endpoint,staff,onClose,onChanged}:{id:string;endpoint:string;staff:boolean;onClose:()=>void;onChanged:()=>void}) {
 const [detail,setDetail]=useState<ConditionDetail|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const [action,setAction]=useState(""),[note,setNote]=useState(""),[items,setItems]=useState<DraftItem[]>([]),[attachments,setAttachments]=useState<Array<{file:File;itemKey:string}>>([]),[review,setReview]=useState(false),[itemPage,setItemPage]=useState(0);
 const [baselineId,setBaselineId]=useState(""),[checkoutId,setCheckoutId]=useState(""),[historyPage,setHistoryPage]=useState(0);
 const mutation=useRef({fingerprint:"",key:""});
 const load=useCallback(async()=>{setLoading(true);try{setDetail(await api<ConditionDetail>(`${endpoint}?id=${encodeURIComponent(id)}`));setError("");}catch(e){setError(message(e));}finally{setLoading(false);}},[endpoint,id]);
 useEffect(()=>{queueMicrotask(()=>void load());},[load]);
 const moveIns=detail?.revisions.filter(r=>r.phase==="MOVE_IN")||[],checkouts=detail?.revisions.filter(r=>r.phase==="CHECKOUT")||[];
 const baseline=moveIns.find(r=>r.id===baselineId)||moveIns[0],checkout=checkouts.find(r=>r.id===checkoutId)||checkouts[0];
 const revisionAction=["SUBMIT","AMEND","CHECKOUT"].includes(action);
 function choose(value:string) {if(!detail)return;setAction(value);setReview(false);setNote("");setAttachments([]);setItemPage(0);setError("");const prior=value==="CHECKOUT"?checkouts[0]:moveIns[0];setItems(detail.record.checklist.map(item=>({...item,condition:prior?.items.find(i=>i.key===item.key)?.condition||"",note:prior?.items.find(i=>i.key===item.key)?.note||""})));}
 function changeItem(key:string,field:"condition"|"note",value:string){setItems(old=>old.map(i=>i.key===key?{...i,[field]:value}:i));}
 async function submit(event:FormEvent) {
  event.preventDefault();if(!detail||!action)return;setError("");
  if(revisionAction&&!review){const invalid=items.findIndex(i=>!i.condition||["WORN","DAMAGED","MISSING","NOT_CHECKED"].includes(i.condition)&&i.note.trim().length<5);if(invalid!==-1){setItemPage(Math.floor(invalid/3));setError(`Complete ${items[invalid].label}; explain wear, damage, missing items or anything not checked.`);return;}setReview(true);return;}
  const input={id,version:detail.record.version,action,note,...(revisionAction?{items}:{}),photoItems:attachments.map(a=>a.itemKey)};
  const fingerprint=JSON.stringify([input,attachments.map(a=>[a.file.name,a.file.size,a.file.lastModified])]);if(mutation.current.fingerprint!==fingerprint)mutation.current={fingerprint,key:crypto.randomUUID()};
  setBusy(true);try{setDetail(await api<ConditionDetail>(endpoint,"PATCH",{...input,mutationId:mutation.current.key},attachments.map(a=>a.file)));setAction("");setNote("");setAttachments([]);setReview(false);setNotice("Saved. The earlier evidence remains in the record history.");onChanged();}catch(e){setError(message(e));}finally{setBusy(false);}
 }
 return <ResidencyDialog open title={detail?.record.reference||"Condition record"} drawer busy={busy} onClose={onClose}><div className="maintenance-detail condition-detail">
  {error&&<p className="residency-alert" role="alert">{error} Your unsent changes remain here. <button type="button" disabled={busy||loading} onClick={()=>void load()}>Refresh record</button></p>}{notice&&<p className="residency-success" role="status">{notice}</p>}{!detail&&!error&&<p role="status">Loading record…</p>}
  {detail&&<><header className="maintenance-heading"><div><span className="maintenance-badge">{LABEL[detail.record.status]}</span><h3>{detail.record.roomLabel} · {detail.record.spaceLabel}</h3><p>{detail.record.propertyName} · {detail.record.studentName}</p></div><button type="button" disabled={busy||loading} onClick={()=>void load()}>Refresh</button></header>
   {detail.record.archivedAt&&<p className="maintenance-service-note">Previous room: transferred on {when(detail.record.archivedAt)}. Move-in evidence is preserved. The new room has a separate checklist.</p>}
   {detail.record.disputeBy&&<div className="condition-disagreement" role="status"><strong>Open disagreement · {detail.record.disputeBy==="STUDENT"?"Resident":"Hostel staff"}</strong><p>{detail.record.disputeNote}</p><small>Acknowledgment does not remove this disagreement. The side that raised it must withdraw it with a reason before closure.</small></div>}
   <p className="maintenance-muted">Record version {detail.record.version} · Updated {when(detail.record.updatedAt)}. Acknowledgment confirms receipt only. No charges or refunds are created.</p>
   <a className="condition-download" href={`${endpoint}/export?id=${encodeURIComponent(id)}`} download>Download condition summary</a>
   {detail.actions.length>0&&<form className="residency-form maintenance-form maintenance-update" onSubmit={submit}><fieldset disabled={busy||loading}>
    <label>Next action<select value={action} onChange={e=>choose(e.target.value)}><option value="">Choose an action</option>{detail.actions.map(a=><option key={a} value={a}>{a==="WITHDRAW"&&!staff?"Withdraw my disagreement":LABEL[a]}</option>)}</select></label>
    {action&&<>{revisionAction&&<><ol className="maintenance-steps"><li aria-current={!review?"step":undefined}>1 · Inspect &amp; record</li><li aria-current={review?"step":undefined}>2 · Review &amp; save</li></ol>
     {review?<div className="condition-review"><h4>{action==="CHECKOUT"?"Review checkout inspection":"Review move-in evidence"}</h4>{items.map(item=><div key={item.key}><strong>{item.label}</strong><span>{LABEL[item.condition]}</span>{item.note&&<p>{item.note}</p>}</div>)}<p>{attachments.length} private photos · {note||"First move-in submission"}</p></div>:<><p className="maintenance-muted">Check each item as you find it. Use Not checked with a reason when you cannot inspect it. Do not guess.</p><div className="condition-inspection-items">{items.slice(itemPage*3,itemPage*3+3).map(item=><section key={item.key}><h4>{item.label}</h4><label>Condition<select value={item.condition} onChange={e=>changeItem(item.key,"condition",e.target.value)}><option value="">Choose condition</option>{CONDITION_VALUES.map(value=><option value={value} key={value}>{LABEL[value]}</option>)}</select></label><label>Observation<textarea rows={2} maxLength={300} value={item.note} onChange={e=>changeItem(item.key,"note",e.target.value)} placeholder="Describe what you observed. Required for wear, damage, missing or not checked."/></label></section>)}</div><nav className="residency-pagination" aria-label="Checklist items"><span>Items {itemPage*3+1}–{Math.min(items.length,itemPage*3+3)} of {items.length}</span><div><button type="button" disabled={itemPage===0||busy} onClick={()=>setItemPage(itemPage-1)}>Previous items</button><button type="button" disabled={(itemPage+1)*3>=items.length||busy} onClick={()=>setItemPage(itemPage+1)}>Next items</button></div></nav></>}
    </>}
    {!review&&<><label>{action==="SUBMIT"||action==="ACKNOWLEDGE"||action==="ACK_CHECKOUT"?"Overall note (optional)":"Explanation (required)"}<textarea rows={3} maxLength={1500} value={note} required={!["SUBMIT","ACKNOWLEDGE","ACK_CHECKOUT"].includes(action)} minLength={!["SUBMIT","ACKNOWLEDGE","ACK_CHECKOUT"].includes(action)?5:undefined} onChange={e=>setNote(e.target.value)} placeholder={action==="AMEND"?"Explain what changed from the previous submission.":"Add information visible to the resident and authorized hostel staff."}/></label>
     {["SUBMIT","AMEND","CHECKOUT","COMMENT","DISPUTE"].includes(action)&&detail.photos.length<30&&<><PhotoPicker maxTotal={30} photos={attachments.map(a=>a.file)} disabled={busy||loading} onChange={files=>setAttachments(old=>files.map(file=>old.find(a=>a.file===file)||{file,itemKey:""}))}/>{attachments.map((attachment,index)=><label key={index}>Photo location · {attachment.file.name}<select value={attachment.itemKey} onChange={e=>setAttachments(old=>old.map((a,i)=>i===index?{...a,itemKey:e.target.value}:a))}><option value="">Whole room / general evidence</option>{detail.record.checklist.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label>)}</>}
    </>}
    {["ACKNOWLEDGE","ACK_CHECKOUT"].includes(action)&&<p>This records that you received this version. You can still raise a disagreement about any observation.</p>}{action==="CLOSE"&&<p>Close only after departure, both inspections are acknowledged and no disagreement remains. This action does not settle money.</p>}
    <footer>{review&&<button type="button" onClick={()=>setReview(false)}>Edit inspection</button>}<button type="submit" className="maintenance-primary">{busy?"Saving…":revisionAction&&!review?"Review inspection":review?"Save inspection":LABEL[action]}</button></footer></>}
   </fieldset></form>}
   {moveIns.length>0&&<section className="condition-comparison"><h4>Move-in &amp; checkout comparison</h4><div className="maintenance-filters"><label>Move-in version<select value={baseline?.id||""} onChange={e=>setBaselineId(e.target.value)}>{moveIns.map(r=><option value={r.id} key={r.id}>Revision {r.revision}{r.revision===1?" · original":""} · {when(r.createdAt)}</option>)}</select></label>{checkouts.length>0&&<label>Checkout version<select value={checkout?.id||""} onChange={e=>setCheckoutId(e.target.value)}>{checkouts.map(r=><option value={r.id} key={r.id}>Revision {r.revision} · {when(r.createdAt)}</option>)}</select></label>}</div><p className="maintenance-muted">Move-in receipt: {detail.record.moveInAck===detail.record.moveInRevision?"latest version acknowledged":"awaiting staff"}. Checkout receipt: {detail.record.checkoutRevision?detail.record.checkoutAck===detail.record.checkoutRevision?"latest version acknowledged":"awaiting resident":"not recorded"}.</p><div className="condition-comparison-grid">{detail.record.checklist.map(item=>{const before=baseline?.items.find(i=>i.key===item.key),after=checkout?.items.find(i=>i.key===item.key);return <article key={item.key}><h5>{item.label}</h5><div><span>MOVE-IN</span><strong>{before?LABEL[before.condition]:"Not recorded"}</strong><p>{before?.note||"No additional note"}</p></div><div className={after&&before?.condition!==after.condition?"condition-changed":""}><span>CHECKOUT</span><strong>{after?LABEL[after.condition]:"Not recorded"}</strong><p>{after?.note||"No additional note"}</p></div></article>;})}</div><p className="maintenance-muted">Recorded by {baseline?.authorName} at move-in{checkout?` and ${checkout.authorName} at checkout`:""}. A changed observation does not establish responsibility or a charge.</p></section>}
   <details className="condition-history"><summary>Activity &amp; private photos · {detail.events.length} updates</summary><div className="maintenance-history"><ol>{detail.events.slice(historyPage*10,historyPage*10+10).map(event=><li key={event.id}><div><strong>{LABEL[event.action]||event.action} · v{event.version}</strong><time dateTime={event.createdAt}>{when(event.createdAt)}</time></div><small>{event.actorName} · {event.actorType==="STUDENT"?"Resident":"Hostel staff"}</small>{event.note&&<p className="maintenance-prose">{event.note}</p>}<div className="maintenance-photos">{detail.photos.filter(p=>p.eventId===event.id).map(photo=><a href={photo.url} key={photo.id} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{photo.name} · {detail.record.checklist.find(i=>i.key===photo.itemKey)?.label||"Whole room"} ↗</a>)}</div></li>)}</ol></div>{detail.events.length>10&&<nav className="residency-pagination" aria-label="Activity pages"><span>Page {historyPage+1} of {Math.ceil(detail.events.length/10)}</span><div><button type="button" disabled={!historyPage} onClick={()=>setHistoryPage(historyPage-1)}>Newer</button><button type="button" disabled={(historyPage+1)*10>=detail.events.length} onClick={()=>setHistoryPage(historyPage+1)}>Older</button></div></nav>}<p className="maintenance-muted">Private photo links expire after five minutes. Refresh the record to renew them. Original evidence stays attached to its recorded version.</p></details>
  </>}
 </div></ResidencyDialog>;
}
function ChecklistSettings({endpoint,properties,onClose}:{endpoint:string;properties:Property[];onClose:()=>void}) {
 const [property,setProperty]=useState(properties[0]?.id||""),[config,setConfig]=useState<ConditionConfig|null>(null),[labels,setLabels]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!property)return;setBusy(true);setConfig(null);setError("");try{const r=await api<{config:ConditionConfig}>(`${endpoint}/settings?propertyId=${encodeURIComponent(property)}`);setConfig(r.config);setLabels(r.config.checklist.map(i=>i.label).join("\n"));}catch(e){setError(message(e));}finally{setBusy(false);}},[endpoint,property]);
 useEffect(()=>{queueMicrotask(()=>void load());},[load]);
 async function save(event:FormEvent){event.preventDefault();if(!config)return;setBusy(true);setError("");setNotice("");try{const result=await api<{config:ConditionConfig}>(`${endpoint}/settings`,"PATCH",{...config,checklist:labels.split("\n").map(s=>s.trim()).filter(Boolean)});setConfig(result.config);setNotice("Saved. Existing records keep their original checklist.");}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <ResidencyDialog open title="Condition checklist settings" busy={busy} onClose={onClose}><form className="residency-form maintenance-form" onSubmit={save}><label>Property<select value={property} disabled={busy} onChange={e=>{setProperty(e.target.value);setNotice("");}}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{!property&&<p>Add a property first.</p>}{config&&<fieldset disabled={busy}>{!config.platformEnabled&&<p className="maintenance-service-note">The platform switch is off. Prepare the checklist here; students can open new records once both switches are on.</p>}<label className="maintenance-check"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>Allow new condition records</label><label>Inventory checklist · one item per line<textarea rows={10} maxLength={1220} required value={labels} onChange={e=>setLabels(e.target.value)}/></label><p>Use 1–20 unique items, up to 60 characters each. Include the bed, mattress, furniture, locks, sockets and relevant shared facilities. Changes apply to new handovers; existing checklists remain intact.</p><button type="submit" className="maintenance-primary">{busy?"Saving…":"Save checklist"}</button></fieldset>}{error&&<p className="residency-alert" role="alert">{error} <button type="button" disabled={busy} onClick={()=>void load()}>Reload settings</button></p>}{notice&&<p className="residency-success" role="status">{notice}</p>}</form></ResidencyDialog>;
}
