"use client";
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
import { ArrowsLeftRight,CalendarBlank,ArrowRight } from '@/components/ui/MaterialIcon';
import { ResidencyDialog } from './ResidencyDialog';
import { STAY_REQUEST_LABELS as LABEL,type StayDestination,type StayOffer,type StayRequest,type StayRequestConfig,type StayRequestDetail,type StayRequestKind } from '@/lib/hostel-engine/stay-request-types';
import './maintenance.css';
import './stay-plans.css';

type Property={id:string;name:string};
type List={records:StayRequest[];pagination:{page:number;pages:number;total:number};config?:StayRequestConfig};
const money=(n:number)=>new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS'}).format(n/100);
const when=(s:string)=>new Date(s).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});
const date=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString('en-GB',{dateStyle:'medium'}):'Not configured';
const kindName=(kind:string)=>kind==='MOVE'?'Room change':'Next-year renewal';
const ACTION:Record<string,string>={REVIEW:'Start review',OFFER:'Send an offer',ACCEPT:'Accept offer',FULFILL:'Complete room handover',CANCEL:'Cancel request',DECLINE:'Decline with a reason'};
const failure=(error:unknown)=>error instanceof Error?error.message:'The request could not be completed.';
async function api<T>(url:string,method='GET',body?:object):Promise<T>{const response=await fetch(url,{method,credentials:'same-origin',cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'The request could not be completed. Try again.');return result;}
function useMutation(){const state=useRef({payload:'',key:''});return (body:object)=>{const payload=JSON.stringify(body);if(state.current.payload!==payload)state.current={payload,key:crypto.randomUUID()};return {...body,mutationId:state.current.key};};}
export function StayPlansPanel({reference,properties=[]}:{reference?:string;properties?:Property[]}){
 const staff=!reference,endpoint=staff?'/api/console/hostel/stay-requests':'/api/hostel/stay-requests';
 const [property,setProperty]=useState(properties[0]?.id||''),[status,setStatus]=useState('OPEN'),[page,setPage]=useState(1),[data,setData]=useState<List|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const [selected,setSelected]=useState(''),[create,setCreate]=useState<StayRequestKind|null>(null),[settings,setSettings]=useState(false);const sequence=useRef(0),trigger=useRef<HTMLButtonElement|null>(null);
 const load=useCallback(async()=>{const seq=++sequence.current;setLoading(true);try{const result=await api<List>(`${endpoint}?${new URLSearchParams({status,page:String(page),...(reference?{reference}:{propertyId:property})})}`);if(seq===sequence.current){setData(result);setError('');}}catch(e){if(seq===sequence.current)setError(failure(e));}finally{if(seq===sequence.current)setLoading(false);}},[endpoint,reference,property,status,page]);
 useEffect(()=>{const ref=sequence;queueMicrotask(()=>void load());return()=>{ref.current++;};},[load]);
 function close(){setSelected('');setCreate(null);setSettings(false);void load();requestAnimationFrame(()=>trigger.current?.focus());}
 const config=data?.config,enabled=config?.platformEnabled&&config.eligible;
 return <section className="maintenance-panel stay-plans" aria-label="Stay plans">
  <header className="maintenance-heading"><div><span className="maintenance-eyebrow"><CalendarBlank size={18} aria-hidden/> {staff?'STAY MANAGEMENT':'YOUR NEXT CHAPTER'}</span><h3>{staff?'Manage stay plans':'Plan your next stay'}</h3><p>{staff?'Review requests, agree the details and arrange a smooth handover.':'A different room or another academic year, with every detail agreed together.'}</p></div><div className="maintenance-actions"><button type="button" disabled={loading} onClick={()=>void load()}>Refresh</button>{staff&&config?.isOwner&&<button type="button" onClick={e=>{trigger.current=e.currentTarget;setSettings(true);}}>Request settings</button>}</div></header>
  {!staff&&<div className="stay-plan-choices"><article><ArrowsLeftRight size={25} aria-hidden/><h4>Find a better fit</h4><p>Request another bed at the same rent and utilities. Staff will arrange the handover after you accept.</p><button type="button" disabled={!enabled||!config?.movesEnabled} onClick={e=>{trigger.current=e.currentTarget;setCreate('MOVE');}}>Request room change <ArrowRight aria-hidden/></button></article><article><CalendarBlank size={25} aria-hidden/><h4>Stay another year</h4><p>{config?.periodId?`Renewal window: ${date(config.opensOn)} – ${date(config.closesOn)}.`:'Your hostel will announce its next renewal window here.'} Review next year’s price before checkout.</p><button type="button" disabled={!enabled||!config?.renewalOpen} onClick={e=>{trigger.current=e.currentTarget;setCreate('RENEWAL');}}>Request renewal <ArrowRight aria-hidden/></button></article></div>}
  {!staff&&config&&(!enabled||!config.movesEnabled&&!config.renewalOpen)&&<p className="maintenance-service-note">New requests need a current paid stay and enablement by the platform and hostel. Renewals also need an open window. Existing requests remain available below.</p>}
  <div className="maintenance-filters">{staff&&<label>Property<select value={property} onChange={e=>{setProperty(e.target.value);setPage(1);}}><option value="">All properties</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Show<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="OPEN">Open requests</option><option value="">All requests</option></select></label></div>
  {error&&<p className="residency-alert" role="alert">{error}</p>}{loading&&<p role="status" className="maintenance-muted">Loading stay plans…</p>}
  <div className="stay-plan-list" aria-busy={loading}>{data?.records.map(record=><button className="stay-plan-row" type="button" key={record.id} onClick={e=>{trigger.current=e.currentTarget;setSelected(record.id);}}><span className="stay-plan-icon">{record.kind==='MOVE'?<ArrowsLeftRight size={23} aria-hidden/>:<CalendarBlank size={23} aria-hidden/>}</span><span><strong>{kindName(record.kind)}</strong><small>{staff?record.studentName+' · ':''}{record.propertyName} · {record.reference}</small>{record.offer&&<small>{record.offer.roomLabel} · {record.offer.spaceLabel} · {record.offer.periodName}</small>}</span><span className="maintenance-badge">{LABEL[record.status]}</span><ArrowRight size={20} aria-hidden/></button>)}</div>
  {!loading&&!data?.records.length&&!error&&<div className="maintenance-empty"><CalendarBlank size={30} aria-hidden/><h4>No {status?'open ':''}stay requests</h4><p>{staff?'Student requests will appear here for review.':'Your room-change requests and renewals will appear here.'}</p></div>}
  {data&&data.pagination.total>0&&<nav className="residency-pagination" aria-label="Stay request pages"><span>{data.pagination.total} requests · Page {data.pagination.page} of {data.pagination.pages}</span><div><button type="button" disabled={loading||page<=1} onClick={()=>setPage(page-1)}>Previous</button><button type="button" disabled={loading||page>=data.pagination.pages} onClick={()=>setPage(page+1)}>Next</button></div></nav>}
  <p className="maintenance-muted">A request or offer does not reserve a bed. Renewal checkout holds it for 10 minutes; payment must be verified. Different-price room changes are not available.</p>
  {create&&reference&&<NewStayRequest endpoint={endpoint} reference={reference} kind={create} onClose={close}/>}
  {selected&&<StayRequestDrawer endpoint={endpoint} id={selected} staff={staff} onClose={close} onChanged={()=>void load()}/>}
  {settings&&config&&<StaySettings endpoint={endpoint} initial={config} onClose={close}/>}
 </section>;
}
function DestinationPicker({endpoint,reference,kind,value,onChange,onSelected}:{endpoint:string;reference:string;kind:string;value:string;onChange:(value:string)=>void;onSelected?:(value:StayDestination|undefined)=>void}){
 const [search,setSearch]=useState(''),[destinations,setDestinations]=useState<StayDestination[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);const sequence=useRef(0);
 useEffect(()=>{const sequenceRef=sequence;const seq=++sequenceRef.current,timer=setTimeout(()=>{setLoading(true);void api<{destinations:StayDestination[]}>(`${endpoint}?${new URLSearchParams({mode:'options',reference,kind,q:search})}`).then(r=>{if(seq===sequence.current){setDestinations(r.destinations);setError('');}}).catch(e=>{if(seq===sequence.current)setError(failure(e));}).finally(()=>{if(seq===sequence.current)setLoading(false);});},250);return()=>{clearTimeout(timer);sequenceRef.current++;};},[endpoint,reference,kind,search]);
 return <div className="stay-destinations"><label>Find a room or bed<input type="search" maxLength={80} value={search} onChange={e=>{setSearch(e.target.value);onChange('');onSelected?.(undefined);}} placeholder="Search room label"/></label><label>Preferred destination<select value={value} onChange={e=>{onChange(e.target.value);onSelected?.(destinations.find(d=>d.listingId===e.target.value));}} disabled={loading}><option value="">Choose a bed or describe a preference</option>{value&&!destinations.some(d=>d.listingId===value)&&<option value={value}>Previously selected bed · availability will be checked</option>}{destinations.map(d=><option key={d.listingId} value={d.listingId}>{d.roomLabel} · {d.spaceLabel} · {money(d.total)} / year</option>)}</select></label><small>{loading?'Checking availability…':destinations.length?`Showing up to 50 available beds. Search to narrow the list.`:'No available matches. You can still describe your preference in a new request.'}</small>{error&&<p role="alert" className="residency-alert">{error}</p>}</div>;
}
function NewStayRequest({endpoint,reference,kind,onClose}:{endpoint:string;reference:string;kind:StayRequestKind;onClose:()=>void}){
 const [listingId,setListingId]=useState(''),[destination,setDestination]=useState<StayDestination>(),[preference,setPreference]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);const mutate=useMutation();
 async function submit(e:FormEvent){e.preventDefault();if(!review){setReview(true);return;}setBusy(true);setError('');try{await api(endpoint,'POST',mutate({reference,kind,listingId,preference}));setDone(true);}catch(e){setError(failure(e));}finally{setBusy(false);}}
 return <ResidencyDialog open title={kindName(kind)} onClose={onClose} busy={busy}><form className="residency-form maintenance-form" onSubmit={submit}>{done?<div className="stay-complete"><strong>Request sent</strong><p>Hostel staff will review your preference and respond here. Your current stay is unchanged.</p><button type="button" onClick={onClose}>View my requests</button></div>:<><ol className="maintenance-steps"><li aria-current={!review?'step':undefined}>1 · Your preference</li><li aria-current={review?'step':undefined}>2 · Review &amp; send</li></ol><fieldset disabled={busy}>{review?<div className="stay-review"><h4>Review your request</h4><p><strong>{destination?`${destination.roomLabel} · ${destination.spaceLabel}`:'Let staff suggest a suitable bed'}</strong></p><p className="maintenance-prose">{preference}</p><p>Staff will send an offer for your acceptance. This request does not reserve a bed or take payment.</p></div>:<><DestinationPicker endpoint={endpoint} reference={reference} kind={kind} value={listingId} onChange={setListingId} onSelected={setDestination}/><label>Tell staff what you need<textarea rows={4} minLength={5} maxLength={1000} required value={preference} onChange={e=>setPreference(e.target.value)} placeholder={kind==='MOVE'?'Explain your preferred room, accessibility needs or reason for moving.':'Would you like to keep this bed or discuss another option for next year?'}/></label></>}<footer>{review&&<button type="button" onClick={()=>setReview(false)}>Edit request</button>}<button type="submit" className="maintenance-primary">{busy?'Sending…':review?'Send request':'Review request'}</button></footer></fieldset></>}{error&&<p className="residency-alert" role="alert">{error} Your draft is still here.</p>}</form></ResidencyDialog>;
}
function OfferSummary({offer,kind,expiresAt}:{offer:StayOffer;kind:string;expiresAt:string}){return <section className="stay-offer"><span className="maintenance-eyebrow">{kind==='RENEWAL'?'NEXT ACADEMIC YEAR':'ROOM CHANGE OFFER'}</span><h4>{offer.roomLabel} · {offer.spaceLabel}</h4><p>{offer.periodName} · {date(offer.startsOn)} – {date(offer.endsOn)}</p><dl><div><dt>Annual rent per student</dt><dd>{money(offer.price)}</dd></div><div><dt>Utilities</dt><dd>{money(offer.utilitiesFee)}</dd></div><div><dt>{kind==='RENEWAL'?'Total for the new year':'Existing paid annual total'}</dt><dd>{money(offer.total)}</dd></div><div><dt>Due on acceptance</dt><dd>{kind==='RENEWAL'?money(offer.total):money(0)}</dd></div></dl><small>Accept by {when(expiresAt)}. Availability is checked again when you accept.</small>{kind==='RENEWAL'?<p>This creates a separate booking for the new year. Your current stay continues. The existing hostel cancellation policy applies: 100% at least 30 days before the year starts, 50% at 7–29 days, and 0% within 7 days, subject to the platform’s reviewed exceptions. <a href="/hostel/help" target="_blank" rel="noreferrer">Read the booking guide</a>.</p>:<p>No additional rent or utility charge. After acceptance, staff arrange the key handover and preserve your previous room’s condition record.</p>}</section>;}
function StayRequestDrawer({endpoint,id,staff,onClose,onChanged}:{endpoint:string;id:string;staff:boolean;onClose:()=>void;onChanged:()=>void}){
 const [detail,setDetail]=useState<StayRequestDetail|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [action,setAction]=useState(''),[note,setNote]=useState(''),[listingId,setListingId]=useState(''),[destination,setDestination]=useState<StayDestination>(),[expiry,setExpiry]=useState(''),[keysReturned,setKeysReturned]=useState(false),[keyReference,setKeyReference]=useState(''),[review,setReview]=useState(false),[historyPage,setHistoryPage]=useState(0);const mutate=useMutation();
 const load=useCallback(async()=>{setLoading(true);try{setDetail(await api<StayRequestDetail>(`${endpoint}?id=${encodeURIComponent(id)}`));setError('');setReview(false);}catch(e){setError(failure(e));}finally{setLoading(false);}},[endpoint,id]);
 useEffect(()=>{queueMicrotask(()=>void load());},[load]);
 function choose(value:string){setAction(value);setReview(false);setNote('');setListingId('');setDestination(undefined);setError('');setNotice('');}
 async function submit(e:FormEvent){e.preventDefault();if(!detail)return;if(action==='OFFER'&&!listingId){setError('Choose an available destination before sending an offer.');return;}if(!review){setReview(true);return;}setBusy(true);setError('');try{const result=await api<StayRequestDetail>(endpoint,'PATCH',mutate({id,version:detail.record.version,action,note,listingId,expiresAt:action==='OFFER'?new Date(expiry).toISOString():'',keysReturned,keyReference,stayVersion:detail.stayVersion}));setDetail(result);setAction('');setReview(false);setNotice('Saved. The updated status is shown below.');onChanged();}catch(e){setError(failure(e));}finally{setBusy(false);}}
 return <ResidencyDialog open title={detail?.record.reference||'Stay request'} drawer busy={busy} onClose={onClose}><div className="maintenance-detail stay-plan-detail">
 {error&&<p className="residency-alert" role="alert">{error} Your unsent changes remain here. <button type="button" disabled={busy||loading} onClick={()=>void load()}>Refresh request</button></p>}{notice&&<p className="residency-success" role="status">{notice}</p>}{!detail&&!error&&<p role="status">Loading request…</p>}
 {detail&&<><header className="maintenance-heading"><div><span className="maintenance-badge">{LABEL[detail.record.status]}</span><h3>{kindName(detail.record.kind)}</h3><p>{detail.record.propertyName} · {detail.record.studentName}</p></div><button type="button" disabled={busy||loading} onClick={()=>void load()}>Refresh</button></header><p className="maintenance-prose">{detail.record.preference}</p>
 {detail.record.requestedListingId&&<p className="maintenance-muted">Requested bed: {detail.record.requestedDestination||'No longer listed'}. Staff confirm availability when making an offer.</p>}
 {detail.record.offer&&<OfferSummary offer={detail.record.offer} kind={detail.record.kind} expiresAt={detail.record.expiresAt}/>}
 {detail.record.status==='PAYMENT_PENDING'&&<div className="stay-review"><h4>Complete your renewal payment</h4><p>Booking {detail.record.checkoutReference}. The new bed is held for 10 minutes while payment is verified. Refresh your residency if checkout was already completed.</p>{!staff&&detail.record.checkoutUrl?<a className="stay-checkout" href={detail.record.checkoutUrl}>Continue to secure payment <ArrowRight aria-hidden/></a>:<a href={`/hostel/resident?reference=${encodeURIComponent(detail.record.checkoutReference)}`}>Check booking status</a>}</div>}
 {detail.record.status==='PAYMENT_REVIEW'&&<p className="residency-alert">Payment requires platform review. Do not make another payment for this request. Your current-year stay is unchanged.</p>}
 {detail.actions.length>0&&<form className="residency-form maintenance-form" onSubmit={submit}><fieldset disabled={busy||loading}><label>Next action<select value={action} onChange={e=>choose(e.target.value)}><option value="">Choose an action</option>{detail.actions.map(a=><option key={a} value={a}>{ACTION[a]}</option>)}</select></label>{action&&<>{review?<div className="stay-review"><h4>Confirm · {ACTION[action]}</h4>{action==='OFFER'&&<p>{destination?`${destination.roomLabel} · ${destination.spaceLabel} · ${money(destination.total)} per student per year`:listingId}<br/>Accept by {when(new Date(expiry).toISOString())}</p>}<p className="maintenance-prose">{note}</p>{action==='FULFILL'&&<p>Keys returned: {keysReturned?'Yes':'Not recorded'} · New key: {keyReference||'None issued'}</p>}<p>{action==='ACCEPT'?detail.record.kind==='RENEWAL'?'Accept the displayed annual rent and utilities, then complete secure checkout. Payment confirmation is required.':'Accept this bed at your existing price. Arrange the physical move with hostel staff.':action==='OFFER'?'This replaces any earlier offer and requires a fresh student acceptance. The bed remains available until checkout or handover.':'This action will be recorded in the shared activity history.'}</p></div>:<>{action==='OFFER'&&<><DestinationPicker endpoint={endpoint} reference={detail.record.bookingReference} kind={detail.record.kind} value={listingId} onChange={setListingId} onSelected={setDestination}/><label>Offer expires · your local time<input type="datetime-local" required value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><small>Within 14 days and before the renewal window or current academic year closes.</small></>}{action==='FULFILL'&&<><p>Issued key: {detail.keyReference||'None recorded'}</p><label className="maintenance-check"><input type="checkbox" required={Boolean(detail.keyReference)} checked={keysReturned} onChange={e=>setKeysReturned(e.target.checked)}/>Previous key returned</label><label>New key reference (optional)<input maxLength={80} value={keyReference} onChange={e=>setKeyReference(e.target.value)}/></label></>}<label>{['ACCEPT','REVIEW'].includes(action)?'Note (optional)':'Explanation'}<textarea rows={3} maxLength={1000} minLength={['ACCEPT','REVIEW'].includes(action)?undefined:5} required={!['ACCEPT','REVIEW'].includes(action)} value={note} onChange={e=>setNote(e.target.value)}/></label></>}<footer>{review&&<button type="button" onClick={()=>setReview(false)}>Back to details</button>}<button className="maintenance-primary" type="submit">{busy?'Saving…':review?action==='ACCEPT'&&detail.record.kind==='RENEWAL'?'Accept & open checkout':'Confirm action':'Review action'}</button></footer></>}</fieldset></form>}
 <details className="stay-history"><summary>Activity history · {detail.events.length} updates</summary><ol>{detail.events.slice(historyPage*5,historyPage*5+5).map(event=><li key={event.id}><strong>{ACTION[event.action]||LABEL[event.action]||event.action}</strong><small>{event.actorName} · {when(event.createdAt)}</small><p className="maintenance-prose">{event.note}</p>{event.details.startsWith('{')&&<details><summary>Recorded offer</summary><OfferSummary offer={JSON.parse(event.details)} kind={detail.record.kind} expiresAt={JSON.parse(event.details).expiresAt||detail.record.expiresAt}/></details>}</li>)}</ol>{detail.events.length>5&&<nav className="residency-pagination" aria-label="Activity history pages"><button type="button" disabled={!historyPage} onClick={()=>setHistoryPage(historyPage-1)}>Newer</button><span>Page {historyPage+1}</span><button type="button" disabled={(historyPage+1)*5>=detail.events.length} onClick={()=>setHistoryPage(historyPage+1)}>Older</button></nav>}</details>
 </>}
 </div></ResidencyDialog>;
}
function StaySettings({endpoint,initial,onClose}:{endpoint:string;initial:StayRequestConfig;onClose:()=>void}){
 const [config,setConfig]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{config:StayRequestConfig}>(endpoint+'/settings','PATCH',config);setConfig(r.config);setNotice('Settings saved. Changed settings require fresh offers before acceptance.');}catch(e){setError(failure(e));}finally{setBusy(false);}}
 return <ResidencyDialog open title="Stay request settings" busy={busy} onClose={onClose}><form className="residency-form maintenance-form" onSubmit={save}><h3>{config.propertyName}</h3>{!config.platformEnabled&&<p className="maintenance-service-note">The platform switch is off. Prepare your settings here before the pilot is enabled.</p>}<fieldset disabled={busy}><label className="maintenance-check"><input type="checkbox" checked={config.movesEnabled} onChange={e=>setConfig({...config,movesEnabled:e.target.checked})}/>Allow equal-price room-change requests</label><label className="maintenance-check"><input type="checkbox" checked={config.renewalsEnabled} onChange={e=>setConfig({...config,renewalsEnabled:e.target.checked})}/>Allow next-year renewal requests</label>{config.renewalsEnabled&&<><label>Next academic year<select required value={config.periodId} onChange={e=>setConfig({...config,periodId:e.target.value})}><option value="">Choose an academic year</option>{config.periods.map(p=><option value={p.id} key={p.id}>{p.name} · {date(p.startsOn)}</option>)}</select></label><div className="stay-date-fields"><label>Window opens<input type="date" required value={config.opensOn} onChange={e=>setConfig({...config,opensOn:e.target.value})}/></label><label>Window closes<input type="date" required value={config.closesOn} onChange={e=>setConfig({...config,closesOn:e.target.value})}/></label></div><p>Dates use Ghana time (UTC). Close the window before the new year starts. Set each room’s next-year rate and obtain listing approval before making offers.</p></>}<p>Students review a frozen offer and accept it themselves. Renewals follow the existing payment and cancellation policy. Different-price room changes remain unavailable.</p><button type="submit" className="maintenance-primary">{busy?'Saving…':'Save settings'}</button></fieldset>{error&&<p role="alert" className="residency-alert">{error}</p>}{notice&&<p role="status" className="residency-success">{notice}</p>}</form></ResidencyDialog>;
}
