"use client";
import { useCallback, useEffect, useState } from "react";
import { IdentificationCard, Buildings, Wallet } from "@/components/ui/MaterialIcon";
type Document = { id: string; kind: string; uploadedAt: string };
type Owner = { landlordId: string; name: string; organization: string; email: string; ownerRole: string; profileStatus: string; profileReason: string; identityStatus: string; payoutStatus: string; payoutReason: string; payoutSummary: string; documents: Document[] };
type Property = { id: string; name: string; address: string; latitude: number | null; longitude: number | null; roomCount: number; status: string; landlordId: string; affiliationClaim: string; affiliationStatus: string; evidenceNote: string };
async function request(path: string, init?: RequestInit) { const response = await fetch(path, { credentials: "same-origin", cache: "no-store", ...init }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Review could not load."); return data; }
function badge(status: string) { return <span className={`console-badge console-badge-${status.toLowerCase()}`}>{status.replaceAll("_", " ")}</span>; }
export function HostelOnboardingReview() {
  const [owners, setOwners] = useState<Owner[] | null>(null);
  const [properties, setProperties] = useState<Property[] | null>(null);
  const [reasons, setReasons] = useState<Record<string,string>>({});
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const data = await request("/api/console/hostel/onboarding/review"); setOwners(data.owners || []); setProperties(data.properties || []); }, []);
  useEffect(() => { queueMicrotask(() => { void load().catch(cause => setError(cause instanceof Error ? cause.message : "Review queue could not load.")); }); }, [load]);
  async function decideOwner(landlordId: string, step: "PROFILE"|"IDENTITY"|"PAYOUT", action: "APPROVE"|"REJECT") {
    const id = `${landlordId}:${step}`; setBusy(id); setError(""); setNotice("");
    try { await request("/api/console/hostel/onboarding/review", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ landlordId, step, action, reason: reasons[id] || "" }) }); setNotice(`${step.toLowerCase()} ${action.toLowerCase()}d separately.`); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Decision failed."); } finally { setBusy(""); }
  }
  async function decideProperty(propertyId: string, action: "APPROVE"|"REJECT") {
    const id = `property:${propertyId}`; setBusy(id); setError(""); setNotice("");
    try { await request("/api/console/hostel/properties/review", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, action, reason: reasons[id] || "" }) }); setNotice(`Property ${action.toLowerCase()}d separately.`); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Decision failed."); } finally { setBusy(""); }
  }
  const pendingOwners = (owners || []).filter(item => item.profileStatus !== "APPROVED" || item.identityStatus !== "VERIFIED" || item.payoutStatus !== "APPROVED");
  const pendingProperties = (properties || []).filter(item => item.status === "PENDING_REVIEW");
  return <>
    {error && <div className="console-alert" role="alert">{error}</div>}{notice && <div className="console-alert console-alert-ok" role="status">{notice}</div>}
    <section className="console-panel"><h2><IdentificationCard size={18}/>Owner setup reviews {badge(String(pendingOwners.length))}</h2><p className="console-note">Account details, identity evidence and payout destination are three independent decisions. Verify identity only after inspecting both private documents.</p>{owners === null ? <p className="console-empty">Loading owner reviews…</p> : pendingOwners.length === 0 ? <p className="console-empty">No owner setup decisions are pending.</p> : <div className="hostel-review-stack">{pendingOwners.map(owner => <article className="hostel-review-item" key={owner.landlordId}><header><strong>{owner.organization || owner.name}</strong><span>{owner.email} · {owner.ownerRole.replaceAll("_", " ")}</span></header>{(["PROFILE","IDENTITY","PAYOUT"] as const).map(step => { const status = step === "PROFILE" ? owner.profileStatus : step === "IDENTITY" ? owner.identityStatus : owner.payoutStatus; const id = `${owner.landlordId}:${step}`; return <div className="hostel-review-row" key={step}><div><strong>{step === "PROFILE" ? "Account details" : step === "IDENTITY" ? "Owner identity" : "Payout destination"}</strong>{badge(status)}{step === "IDENTITY" && <div className="hostel-review-docs">{owner.documents.map(doc => <a key={doc.id} href={`/api/console/hostel/identity/${encodeURIComponent(doc.id)}`} target="_blank" rel="noreferrer">{doc.kind.toLowerCase()} evidence · {new Date(doc.uploadedAt).toLocaleDateString("en-GB")}</a>)}</div>}{step === "PAYOUT" && <small>{owner.payoutSummary || "No destination saved"}</small>}{step === "PROFILE" && <small>{owner.name} · {owner.ownerRole.replaceAll("_", " ")}</small>}</div><div className="hostel-review-actions"><input aria-label={`Reason for ${owner.name} ${step}`} maxLength={500} placeholder="Reason if returning" value={reasons[id] || ""} onChange={event => setReasons({ ...reasons, [id]: event.target.value })}/><button disabled={Boolean(busy) || status === (step === "IDENTITY" ? "VERIFIED" : "APPROVED")} onClick={() => void decideOwner(owner.landlordId, step, "APPROVE")}>Approve</button><button disabled={Boolean(busy)} onClick={() => void decideOwner(owner.landlordId, step, "REJECT")}>Return</button></div></div>; })}</article>)}</div>}</section>
    <section className="console-panel"><h2><Buildings size={18}/>Property reviews {badge(String(pendingProperties.length))}</h2><p className="console-note">Review the confirmed pin and approved building photos before approving. Rooms are added after setup approval. A UMaT-affiliated claim needs evidence verified by staff.</p>{properties === null ? <p className="console-empty">Loading properties…</p> : pendingProperties.length === 0 ? <p className="console-empty">No properties await review.</p> : <div className="hostel-review-stack">{pendingProperties.map(item => { const id = `property:${item.id}`; return <article className="hostel-review-item" key={item.id}><header><strong>{item.name}</strong><span>{item.address}</span></header><p className="console-note">{item.roomCount} active rooms · Affiliation claim: {item.affiliationClaim.toLowerCase()} · {item.evidenceNote || "No note"}. Photos have their own queue above.</p>{item.latitude !== null && item.longitude !== null && <a className="hostel-review-map" href={`https://www.openstreetmap.org/?mlat=${item.latitude}&mlon=${item.longitude}#map=17/${item.latitude}/${item.longitude}`} target="_blank" rel="noreferrer">Inspect confirmed map pin ↗</a>}<div className="hostel-review-actions"><input aria-label={`Reason for ${item.name}`} maxLength={500} placeholder="Reason if returning" value={reasons[id] || ""} onChange={event => setReasons({ ...reasons, [id]: event.target.value })}/><button disabled={Boolean(busy)} onClick={() => void decideProperty(item.id, "APPROVE")}>Approve property</button><button disabled={Boolean(busy)} onClick={() => void decideProperty(item.id, "REJECT")}>Return</button></div></article>; })}</div>}</section>
    <div className="console-strip"><Wallet size={18}/>A payout destination is required before a student can book. Payout review does not approve identity, property or any bed listing.</div>
  </>;
}
