"use client";
import "@/components/campusRide/hostel/hostel-help.css";
import { HostelHelpAssistant } from "@/components/campusRide/hostel/HostelHelpAssistant";

export function HostelStaffGuide({ role }: { role: string }) {
  const landlord = role === "LANDLORD";
  const moderator = role === "MODERATOR";
  return <div className="hostel-help-layout">
    <div className="hostel-help-lead"><p>HOSTEL OPERATIONS</p><h2>Your role-specific guide</h2><p>These notes describe current Hostel Finder workflows. Approval of one step does not approve the rest.</p></div>
    <HostelHelpAssistant staff/>
    {landlord ? <>
      <section className="hostel-help-card"><h2>Setup and approval gates</h2><ol><li>Submit owner/account details for review.</li><li>Add the property, confirm its pin, add rooms and approved photos, then submit the property.</li><li>Submit identity and authority evidence, then save a payout destination for separate review.</li></ol><p>Identity approval unlocks pricing and listing work. Property approval is needed before bed listings can be submitted. Every bed listing has its own review. Payout approval is required before students can book.</p></section>
      <section className="hostel-help-card"><h2>Rooms, prices, and bulk actions</h2><ul><li>A room has one to six bookable student beds. A bunk unit creates an upper and lower bed.</li><li>Price every bed in a room at the same annual per-bed rate. Utilities are also charged per bed when enabled.</li><li>Use room ranges for repeated layouts, rate ranges for existing rooms, and submission ranges for priced drafts. The interface processes up to 20 rooms at a time and supports resumable ranges up to 100.</li><li>Held, occupied, suspended, missing, or unpriced beds stop the affected submission group. Resolve the issue or narrow the range and retry.</li><li>Adding rooms after approval can return the property to draft. Recheck its status before submitting beds.</li></ul></section>
      <section className="hostel-help-card"><h2>Photos, assistant facts, and students</h2><p>Upload JPEG, PNG, or WebP images up to 6 MB. Up to 12 property images may be stored; photos and floor-plan images need approval before public display. Video walkthrough uploads are not supported.</p><p>Use the AI information desk for accurate property and room facts. Prices should stay in the listing editor. Forwarded questions appear in the staff inbox; a reply is emailed to the student.</p><p>Manage viewing slots, resident messages, announcements, and supported service requests in the landlord workspace. The owner invites or revokes managers and changes the payout destination. Managers must use their own active account.</p></section>
      <section className="hostel-help-card"><h2>Payouts and add-ons</h2><p>Payment, ledger accrual, release eligibility, transfer, and settlement are different states. Check the statement and contact platform support for exceptions. Do not ask a student to repeat a payment while the original is pending.</p><p>The service add-on catalogue is under a product-policy hold while vendor delivery and late-payment handling are unresolved. Do not promise add-on fulfilment until the hold is lifted.</p></section>
    </> : moderator ? <>
      <section className="hostel-help-card"><h2>Listing and trust reviews</h2><p>Review submitted property and bed evidence, then approve or reject with a clear reason the owner can act on. Listing approval only permits public discovery when the year is open, the room and bed are active, and the property is not suspended.</p><p>Use supply signals to prioritize checks; a signal is not proof. Record the evidence and decision. Moderator access does not include payout or refund controls.</p></section>
      <section className="hostel-help-card"><h2>Public reviews and escalation</h2><p>Review content within your role’s permissions. Hide a review only with a recorded reason. Escalate payout, refund, and identity concerns to an administrator. Do not reveal identity documents or full payout details in public replies.</p></section>
    </> : <>
      <section className="hostel-help-card"><h2>Approval and catalogue operations</h2><p>Profile, identity, property, photos, payout destination, and each bed listing are separate review decisions. Keep the academic-year catalogue accurate and avoid overlapping active years.</p><p>Use evidence-based reasons for decisions. Staff-check records reflect review dates; they are not ongoing guarantees of a property’s condition.</p></section>
      <section className="hostel-help-card"><h2>Payout and refund operations</h2><p>Use the audited payout flow and review masked destination details. Reconcile transfer states before retrying; never imply a transfer settled until the provider or manual record confirms it.</p><p>Refund quotes are 100% at least 30 days before the year, 50% 7–29 days before, and 0% inside the final 7 days. An exception needs a reason. Approval and payment settlement are separate.</p></section>
      <section className="hostel-help-card"><h2>Signals, analytics, and add-ons</h2><p>Analytics and risk signals support human review. A signal is a triage hint, not a decision. The add-on service catalogue remains under a product-policy hold pending vendor and late-payment decisions.</p></section>
    </>}
  </div>;
}
