"use client";
import "@/components/campusRide/hostel/hostel-help.css";
import { HostelHelpAssistant } from "@/components/campusRide/hostel/HostelHelpAssistant";

export function HostelStaffGuide({ role }: { role: string }) {
  const landlord = role === "LANDLORD";
  const moderator = role === "MODERATOR";
  return <div className="hostel-help-layout">
    <div className="hostel-help-lead"><p>HOSTEL OPERATIONS</p><h2>Your role-specific guide</h2><p>These notes describe current Hostel Finder workflows. Approval of one step does not approve the rest.</p></div>
    <HostelHelpAssistant staff/>
    {landlord ? <>
      <section className="hostel-help-card"><h2>Setup and approval gates</h2><ol><li>Submit owner/account details for review.</li><li>Add the property, confirm its pin, add rooms and approved photos, then submit the property.</li><li>Submit identity and authority evidence, then save a payout destination for separate review.</li></ol><p>Identity approval unlocks pricing and listing work. Property approval is needed before bed listings can be submitted. Every bed listing has its own review. Payout approval is required before students can book.</p></section>
      <section className="hostel-help-card"><h2>Rooms, prices, and bulk actions</h2><ul><li>A room has one to six bookable student beds. A bunk unit creates an upper and lower bed.</li><li>Price every bed in a room at the same annual per-bed rate. Utilities are also charged per bed when enabled.</li><li>Use room ranges for repeated layouts, rate ranges for existing rooms, and submission ranges for priced drafts. The interface processes up to 20 rooms at a time and supports resumable ranges up to 100.</li><li>Held, occupied, suspended, missing, or unpriced beds stop the affected submission group. Resolve the issue or narrow the range and retry.</li><li>Adding rooms after approval can return the property to draft. Recheck its status before submitting beds.</li></ul></section>
      <section className="hostel-help-card"><h2>Photos, assistant facts, and students</h2><p>Upload JPEG, PNG, or WebP images up to 6 MB. Up to 12 property images may be stored; photos and floor-plan images need approval before public display. Video walkthrough uploads are not supported.</p><p>Use the AI information desk for accurate property and room facts. Prices should stay in the listing editor. Forwarded questions appear in the staff inbox; a reply is emailed to the student.</p><p>Manage viewing slots, resident messages, announcements, and supported service requests in the landlord workspace. The owner invites or revokes managers and changes the payout destination. Managers must use their own active account.</p></section>
      <section className="hostel-help-card"><h2>Arrivals, keys, and departures</h2><ol><li>Open Residents &amp; Services. Filter by property, academic year, or status; search by name, room, email, or reference. Each page shows up to 20 residents.</li><li>Select View resident to open the details panel. Set the expected arrival within the booked academic year. Check in when the student arrives and record the key reference if issued.</li><li>At checkout, confirm any issued key has been returned and add an inspection or departure note. Record a no-show only after the expected arrival date.</li><li>For a bed transfer, select an approved free bed in the same property and academic year at the same rent and utilities price. Confirm return of the old key and record the new key if issued.</li></ol><p>Changes record the staff account and protect against conflicting edits. Checkout and no-show release the bed; the payment record remains unchanged. An open refund blocks occupancy changes, and refund approval remains an administrator action.</p></section>
      <section id="stay-plans" className="hostel-help-card"><h2>Room changes and next-year renewals</h2><ol><li>Open Residents &amp; Services → Stay plans. Select a property. The owner uses Request settings to enable requests and set a future academic year and renewal window. Platform enablement is also required.</li><li>Set and submit each room’s rent for that academic year. Occupied current-year beds can have separate next-year listings, subject to availability and approval.</li><li>Review the student’s preference. Offer an approved available bed, include a reason, and set an expiry within 14 days and before the window or current year closes.</li><li>Wait for student acceptance. A replacement offer always needs fresh acceptance. Offers do not hold inventory.</li><li>Complete accepted equal-price moves with key-return confirmation, the new key reference where applicable and a handover note. Renewal payments are completed by the student through verified checkout.</li></ol><p>Renewals create a separate booking and payout entry. Current checkout preserves next-year claims. Only equal-price room changes are supported. Managers may handle requests; only owners configure property settings. Turning the feature off preserves accepted handovers, payment processing and history.</p></section>
      <section id="conditions" className="hostel-help-card"><h2>Move-in and checkout evidence</h2><p>Open Residents &amp; Services → Condition records. The owner uses Checklist settings to configure 1–20 unique inventory items and enable the property. Platform enablement is also required for new records. Template changes do not rewrite existing checklists.</p><ol><li>Review the student’s move-in record. Acknowledge receipt, request clarification or record a disagreement.</li><li>Record checkout using the same checklist, with notes and optional private photos. The resident acknowledges the latest inspection version.</li><li>Compare original or amended move-in evidence with checkout. Close only after departure or transfer, both current receipts and no open disagreement.</li></ol><p>Acknowledgment does not imply agreement. Only the side that raised a disagreement can withdraw it with a reason; a later disagreement reopens a closed record. Transfers atomically preserve existing evidence and start a new-room handover. Download an authenticated summary for the record. No action creates charges or refunds. Existing records and transfer handovers continue when new records are disabled.</p></section>
      <section id="maintenance" className="hostel-help-card"><h2>Maintenance desk</h2><ol><li>Open Residents &amp; Services → Maintenance. The owner uses Property settings to opt in, set service hours and choose a first-response target of 1–168 elapsed hours. The administrator must also enable the platform switch.</li><li>Filter by property, category, urgency, status, assigned staff, overdue response or escalation. The queue shows 20 reports per page.</li><li>Open a report, acknowledge it and assign an active owner or manager from your hostel. Respect the resident’s access preference. Start work, ask for details or add a reply as needed.</li><li>Record a clear repair note when marking the report resolved. The student confirms resolution or reopens with a reason. Cancellation needs a reason and ends the report.</li></ol><p>Photos and notes are private to the reporter and authorized staff. History records who made each change; refresh before retrying a conflicting edit. Existing reports continue after checkout or disabling new reports. Urgency is not emergency dispatch, and targets run outside service hours too. Email updates are queued, so check the desk directly for current records.</p><p>Assign staff responsibility before a pilot. Maintenance does not activate paid add-ons. The guide assistant explains the workflow; it cannot read or update live reports.</p></section>
      <section className="hostel-help-card"><h2>Payouts and add-ons</h2><p>Payment, ledger accrual, release eligibility, transfer, and settlement are different states. Check the statement and contact platform support for exceptions. Do not ask a student to repeat a payment while the original is pending.</p><p>The service add-on catalogue is under a product-policy hold while vendor delivery and late-payment handling are unresolved. Do not promise add-on fulfilment until the hold is lifted.</p></section>
    </> : moderator ? <>
      <section className="hostel-help-card"><h2>Listing and trust reviews</h2><p>Review submitted property and bed evidence, then approve or reject with a clear reason the owner can act on. Listing approval only permits public discovery when the year is open, the room and bed are active, and the property is not suspended.</p><p>Use supply signals to prioritize checks; a signal is not proof. Record the evidence and decision. Moderator access does not include payout or refund controls.</p></section>
      <section className="hostel-help-card"><h2>Public reviews and escalation</h2><p>Review content within your role’s permissions. Hide a review only with a recorded reason. Escalate payout, refund, and identity concerns to an administrator. Do not reveal identity documents or full payout details in public replies.</p></section>
    </> : <>
      <section className="hostel-help-card"><h2>Approval and catalogue operations</h2><p>Profile, identity, property, photos, payout destination, and each bed listing are separate review decisions. Keep the academic-year catalogue accurate and avoid overlapping active years.</p><p>Use evidence-based reasons for decisions. Staff-check records reflect review dates; they are not ongoing guarantees of a property’s condition.</p></section>
      <section className="hostel-help-card"><h2>Payout and refund operations</h2><p>Use the audited payout flow and review masked destination details. Reconcile transfer states before retrying; never imply a transfer settled until the provider or manual record confirms it.</p><p>Refund quotes are 100% at least 30 days before the year, 50% 7–29 days before, and 0% inside the final 7 days. An exception needs a reason. Approval and payment settlement are separate.</p></section>
      <section id="stay-plans" className="hostel-help-card"><h2>Stay plans rollout</h2><p>Hostel stay plans starts off. Pilot with owner opt-in, approved next-year listings and an explicit renewal window. Verify both current and future reservations, cancellation, payout accrual and key handover before broader enablement. Different-price moves remain disabled.</p></section>
      <section id="conditions" className="hostel-help-card"><h2>Condition record rollout</h2><p>The Hostel condition records switch starts off. Pilot with an owner-configured checklist and property opt-in. Disabling new records preserves existing evidence, review and transfer handovers. Acknowledgment is not agreement, and records never create charges or refunds.</p></section>
      <section id="maintenance" className="hostel-help-card"><h2>Maintenance rollout</h2><p>The Hostel maintenance requests platform switch starts off. Enable it only for a prepared pilot: the owner must opt in, configure service hours and an elapsed-hour response target, and name responsible staff. New reports require both switches and a current paid stay. Disabling the switch preserves existing reports and follow-up. Maintenance reports and photos remain in the authorized hostel workspace.</p></section>
      <section className="hostel-help-card"><h2>Signals, analytics, and add-ons</h2><p>Analytics and risk signals support human review. A signal is a triage hint, not a decision. The add-on service catalogue remains under a product-policy hold pending vendor and late-payment decisions.</p></section>
    </>}
  </div>;
}
