import type { Metadata } from "next";
import Link from "next/link";
import { CampusShell } from "@/components/campusRide/shared/CampusShell";
import { HostelHelpAssistant } from "@/components/campusRide/hostel/HostelHelpAssistant";
import "@/components/campusRide/hostel/hostel-help.css";

export const metadata: Metadata = {
  title: "Hostel Finder Help | UMaTeXPRESS",
  description: "How to compare hostels, book a bed, request a visit, use alerts, and understand prices and refunds.",
};

export default function HostelHelpPage() {
  return <CampusShell area="HOSTELFINDER HELP" title="Hostel Finder help" subtitle="Clear steps for finding, visiting, booking, and managing your student stay.">
    <div className="hostel-help-layout">
      <div className="hostel-help-lead"><p>STUDENT GUIDE</p><h2>Find a place with the details in front of you</h2><p>Browse approved properties without signing in. Beds and prices appear after separate listing approval. Use these steps to compare a room, ask questions, and book when you are ready.</p><div className="hostel-help-links"><Link href="/hostel">Browse hostels</Link><Link href="/hostel/resident">Open my residency</Link></div></div>
      <HostelHelpAssistant/>
      <section className="hostel-help-card"><h2>Compare hostels</h2><ol><li>Choose an open academic year. Search by name or area, then filter by distance, yearly price, available beds, or utilities.</li><li>Open a property to see approved photos, reviews, staff-check dates and travel estimates. Approved rooms and bed prices appear when available.</li><li>The card distance is a straight-line estimate. A walking route and time are shown separately when routing data is available.</li></ol><p>Browse without an account. Sign in to save a hostel, request a viewing, or book.</p></section>
      <section className="hostel-help-card"><h2>Understand the price and beds</h2><ul><li>The price is for one student bed for one academic year. Beds in the same room have the same yearly rent.</li><li>A bunk unit has a lower and an upper bed. Each is a separate bed space and requires its own booking.</li><li>The displayed total includes utilities only when the property has enabled a per-bed utilities fee. Ask about any charge that is not shown.</li><li>Each student can have one active booking or checkout per academic year. Each student books their own bed.</li></ul></section>
      <section className="hostel-help-card"><h2>Visit or ask before booking</h2><p>Choose an available visit time and sign in to request it. A viewing is free and does not reserve a bed; hostel staff confirm or decline your request.</p><p>Use the property assistant for questions about one hostel. It uses the public listing and facts supplied by that hostel. If it cannot answer, send the question to staff and include an email address for their reply.</p><p>Staff-check dates show when a review record was created. Conditions can change after that check, so confirm important details with the hostel.</p></section>
      <section className="hostel-help-card"><h2>Book and pay</h2><ol><li>Choose a bed and review the annual rent, utilities, and total.</li><li>Sign in with your UMaT student account.</li><li>Select <strong>Hold this bed</strong>. You have ten minutes to finish checkout.</li><li>Complete Paystack checkout. The booking is confirmed after the payment is verified.</li></ol><p>If the hold expires before payment is complete, the bed may be released. A listing may be visible while checkout is paused for payout review.</p></section>
      <section className="hostel-help-card"><h2>Saved hostels and alerts</h2><p>Save up to 20 hostels per student account. Enable alerts to hear when a bed becomes available again or a newer academic year opens at a saved property. Alerts can take time; check the bed again before paying.</p></section>
      <section className="hostel-help-card"><h2>After your booking</h2><p>Open <Link href="/hostel/resident">My Hostel Residency</Link> with the same student account that paid. You can review the confirmed bed, contact your host, read announcements, message staff, and manage eligible service requests.</p><p>Use Current stays or History, then choose Overview, Requests, Messages, or Payments. Pending bookings appear here too. On returning from checkout, the page checks payment; use Check payment if confirmation is delayed. A paid bed starts as Expected arrival. Staff record check-in and checkout separately. Checkout releases the bed but does not issue a refund.</p><p>Paid stays can leave one review. Hostel staff can reply once; platform staff can hide a review with a recorded reason.</p></section>
      <section id="stay-plans" className="hostel-help-card"><h2>Renew or request a room change</h2><ol><li>Open My Hostel Residency → Requests → Stay plans. New requests require a current paid stay and platform/hostel enablement. Renewals also need an open renewal window.</li><li>Choose a bed or describe your preference, review the summary, and send. Staff will review your request.</li><li>Review the offered room, annual rent per student, utilities, total and expiry. Accept before expiry; a request or offer alone does not reserve a bed.</li><li>For an equal-price move, arrange the key handover with staff. Your old room evidence is preserved.</li><li>For a renewal, accept the offer and use Continue to secure payment. The new-year bed has a ten-minute checkout hold and is confirmed only after verified payment. Your current stay continues.</li></ol><p>Changed prices, settings or room assignments require a fresh offer. Do not make another payment while verification is pending. You can cancel before checkout or handover; once renewal checkout starts, follow its separate booking and existing refund policy. Different-price moves are not available. Existing requests remain readable when new requests are paused.</p></section>
      <section id="conditions" className="hostel-help-card"><h2>Your room condition record</h2><ol><li>Open My Hostel Residency → Requests → Room condition. New records require a current paid stay and this feature enabled by the platform and hostel.</li><li>Open the current checklist. Inspect the items, three at a time, and record their condition. Explain wear, damage, missing items or anything you could not check.</li><li>Add optional private photos for an item or the whole room. Review the summary before saving.</li><li>Staff acknowledge receipt or ask for clarification. Amendments preserve every earlier version. At checkout, review the staff inspection and acknowledge receipt or raise a disagreement.</li></ol><p>Acknowledgment does not mean agreement. Only the side that raised a disagreement can withdraw it with a reason. An unresolved disagreement blocks closure; raising one after closure reopens review. These records never create a charge or refund.</p><p>Transfers preserve the old room evidence and open a separate checklist for the new bed when a record already exists. Compare original or amended move-in evidence with checkout, and download the summary from the record. Private photos support JPEG, PNG or WebP, up to 3 of 6 MB per update and 30 per record. Draft edits remain while the panel stays open after a failed upload; retry or remove photos and add them later.</p></section>
      <section id="maintenance" className="hostel-help-card"><h2>Report a maintenance problem</h2><ol><li>In My Hostel Residency, choose your stay and open Requests → Report a problem. New reports require a current paid stay and maintenance enabled by the platform and hostel.</li><li>Choose a category and urgency. Give the exact room/bed or shared-area location, describe what happened and when, and choose an access preference.</li><li>Add optional private photos: JPEG, PNG or WebP, up to 3 per update and 6 MB each, with 10 per report. Export HEIC photos as JPEG first.</li><li>Review the summary and submit. Your report reference and timeline track acknowledgment, assigned staff, replies and repairs.</li><li>When staff mark it resolved, confirm the fix or reopen with an explanation. Use Escalate to owner when the issue needs additional attention.</li></ol><p>Existing reports remain available after checkout or when new reporting is disabled. All reports includes closed and cancelled cases. A cancelled report cannot be reopened. First response targets count elapsed hours, including outside service hours. Updates queue email notifications; delivery may take time.</p><p>An urgent flag does not guarantee emergency response. Contact local emergency services for immediate danger; use the hostel contact shown where verified. The AI help assistant can explain steps and help you structure the description, but cannot view a live report or send it for you.</p><p>Photos stay within the report and are not added to the public property gallery. If an upload fails, retry with the retained draft or remove the photos and add them in a reply later.</p></section>
      <section className="hostel-help-card"><h2>Refund requests</h2><p>Refund requests are reviewed by staff. The current policy quote is:</p><ul><li>30 days or more before the academic year: 100%.</li><li>7 to 29 days before the year: 50%.</li><li>Inside the final 7 days: 0%.</li></ul><p>An administrator may approve an exception with a recorded reason. An approved refund is complete after the payment settles.</p></section>
      <p className="hostel-help-lead">Availability and property details can change. Recheck the selected bed and price immediately before checkout.</p>
    </div>
  </CampusShell>;
}
