#!/usr/bin/env bash
set -euo pipefail

WORKER_NAME="${CLOUDFLARE_WORKER_NAME:-umatexpress}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_IN="$PROJECT_DIR/dist/server/wrangler.json"
CONFIG_OUT="$PROJECT_DIR/dist/server/wrangler.deploy.json"
CONSOLE_HOST="${CLOUDFLARE_CONSOLE_HOST:-}"

# Reads one key from .env, distinguishing "unset" (use the default) from
# "present but empty" (the binding is deliberately disabled), which is exactly
# how the Vite binding plan reads the same file.
env_or_default() {
  local key="$1" fallback="$2" line
  line="$(grep -E "^${key}=" "$PROJECT_DIR/.env" 2>/dev/null | tail -1 || true)"
  if [[ -z "$line" ]]; then
    printf '%s' "$fallback"
    return
  fi
  printf '%s' "${line#*=}" | tr -d '"' | tr -d "'" | xargs || true
}

# The console lives on its own origin. Read it from .env when the shell has not
# exported it, so one file configures local runs and deploys alike.
if [[ -z "$CONSOLE_HOST" && -f "$PROJECT_DIR/.env" ]]; then
  CONSOLE_HOST="$(grep -E '^CLOUDFLARE_CONSOLE_HOST=' "$PROJECT_DIR/.env" | tail -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | xargs || true)"
fi

cd "$PROJECT_DIR"

# Bindings that name an account-side resource must exist before Wrangler can
# deploy a Worker that references them. Creating them here keeps the first
# deploy of a fresh account from failing halfway through, and re-running is a
# no-op.
R2_BINDING="$(env_or_default CLOUDFLARE_R2_BINDING PRIVATE_BUCKET)"
R2_BUCKET="$(env_or_default CLOUDFLARE_R2_BUCKET umatexpress-private)"
QUEUE_BINDING="$(env_or_default CLOUDFLARE_QUEUE_BINDING NOTIFICATION_QUEUE)"
QUEUE_NAME="$(env_or_default CLOUDFLARE_QUEUE umatexpress-notifications)"

ensure_r2_bucket() {
  local bucket="$1" output
  if output="$(wrangler r2 bucket create "$bucket" 2>&1)"; then
    echo "Created R2 bucket '$bucket'."
  elif grep -qiE "already exists|already owned|code: 10004" <<<"$output"; then
    echo "R2 bucket '$bucket' already exists."
  else
    echo "$output" >&2
    echo "Could not create the R2 bucket '$bucket'. Create it in the Cloudflare dashboard or unset CLOUDFLARE_R2_BUCKET to deploy without it." >&2
    return 1
  fi
}

ensure_queue() {
  local queue="$1" output
  if output="$(wrangler queues create "$queue" 2>&1)"; then
    echo "Created queue '$queue'."
  # Cloudflare answers an existing queue with "already taken" (code 11009),
  # which is not the wording it uses for buckets, so match both.
  elif grep -qiE "already exists|already taken|code: 11009" <<<"$output"; then
    echo "Queue '$queue' already exists."
  else
    echo "$output" >&2
    echo "Could not create the queue '$queue'. Create it in the Cloudflare dashboard or unset CLOUDFLARE_QUEUE to deploy without it." >&2
    return 1
  fi
}

if [[ -n "$R2_BINDING" && -n "$R2_BUCKET" ]]; then
  ensure_r2_bucket "$R2_BUCKET"
fi

if [[ -n "$QUEUE_BINDING" && -n "$QUEUE_NAME" ]]; then
  ensure_queue "$QUEUE_NAME"
  ensure_queue "${QUEUE_NAME}-dlq"
fi

npm run build

if [[ ! -f "$CONFIG_IN" ]]; then
  echo "Missing Vinext Cloudflare config: $CONFIG_IN" >&2
  echo "Run npm run build and confirm dist/server/wrangler.json is generated." >&2
  exit 1
fi

if [[ ! -f "$PROJECT_DIR/dist/server/index.js" ]]; then
  echo "Missing Worker entry: $PROJECT_DIR/dist/server/index.js" >&2
  echo "Vinext build completed without the expected server entry point." >&2
  exit 1
fi

if [[ ! -d "$PROJECT_DIR/dist/client" ]]; then
  echo "Missing client assets directory: $PROJECT_DIR/dist/client" >&2
  exit 1
fi

node - "$CONFIG_IN" "$CONFIG_OUT" "$WORKER_NAME" "$CONSOLE_HOST" <<'NODE'
const fs = require("node:fs");
const path = require("node:path");
const [input, output, name, consoleHost] = process.argv.slice(2);
const serverDir = path.dirname(input);
const projectDir = path.dirname(path.dirname(serverDir));
const config = JSON.parse(fs.readFileSync(input, "utf8"));
config.name = name;
config.topLevelName = name;
config.main = path.join(serverDir, "index.js");
config.assets = { directory: path.join(projectDir, "dist/client") };
// A redeploy must never drop the console domain, so the route is written into
// the generated config instead of being added once in the dashboard.
if (consoleHost) {
  config.routes = [{ pattern: `${consoleHost.replace(/^https?:\/\//, "").replace(/\/.*$/, "")}/*`, custom_domain: true }];
} else {
  console.log("CLOUDFLARE_CONSOLE_HOST is not set: deploying without the console custom domain.");
  console.log("The console then only answers on the workers.dev host listed in CONSOLE_HOSTS.");
}
// Bindings are generated by the Vite build from the same environment this
// script reads, so print them rather than re-deriving them: the deployed Worker
// is the one that has to agree with these.
const bindings = [
  config.ai?.binding ? `Workers AI=${config.ai.binding}` : "",
  config.images?.binding ? `Images=${config.images.binding}` : "",
  ...(config.r2_buckets ?? []).map((item) => `R2=${item.binding}:${item.bucket_name}`),
  ...(config.queues?.producers ?? []).map((item) => `Queue=${item.binding}:${item.queue}`),
  ...(config.durable_objects?.bindings ?? []).map((item) => `DurableObject=${item.name}:${item.class_name}`),
  ...(config.services ?? []).map((item) => `Service=${item.binding}:${item.service}`),
  ...(config.mtls_certificates ?? []).map((item) => `mTLS=${item.binding}:${item.certificate_id}`),
].filter(Boolean);
console.log(`Bindings: ${bindings.length ? bindings.join(", ") : "none"}`);
fs.writeFileSync(output, JSON.stringify(config, null, 2));
NODE

wrangler deploy --config "$CONFIG_OUT"
